version: '3'
services:
  aljallab:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    networks:
      - aljallab_network
    ports:
      - "8080:5000"
  selenium:
    image: selenium/standalone-chrome:latest
    networks:
      - aljallab_network
    ports:
      - "4444:4444"
networks:
  aljallab_network:
    driver: bridge
